import type { AnimatedProperty, Graphics3DAnimatedProperty, Graphics3DAnimationTarget, Graphics3DCamera, Graphics3DMesh, Graphics3DTrack, Graphics3DView, Graphics3DWorld, Keyframe, SceneTimeline, Track } from "./types";
function ease(x:number,e:Keyframe["easing"]="linear"){if(e==="ease-in")return x*x;if(e==="ease-out")return 1-(1-x)*(1-x);if(e==="ease-in-out")return x<.5?2*x*x:1-2*(1-x)*(1-x);return x;}
export function interpolate3DKeyframes(keyframes:Keyframe[],time:number):number|undefined{if(!keyframes.length)return undefined;const a=[...keyframes].sort((x,y)=>x.time-y.time);if(time<=a[0].time)return a[0].value;if(time>=a[a.length-1].time)return a[a.length-1].value;for(let i=1;i<a.length;i++)if(time<=a[i].time){const p=a[i-1],n=a[i],x=ease((time-p.time)/(n.time-p.time),n.easing);return p.value+(n.value-p.value)*x;}return a[a.length-1].value;}
export function create3DTrack(id:string,targetType:Graphics3DAnimationTarget,targetId:string,property:Graphics3DAnimatedProperty,keyframes:Keyframe[]=[]):Graphics3DTrack{return{id,targetType,targetId,property,keyframes:[...keyframes].sort((a,b)=>a.time-b.time)}}
export function evaluate3DProperty(tracks:Graphics3DTrack[]|undefined,targetType:Graphics3DAnimationTarget,targetId:string,property:Graphics3DAnimatedProperty,time:number,base:number):number{const track=tracks?.find(t=>t.targetType===targetType&&t.targetId===targetId&&t.property===property);return interpolate3DKeyframes(track?.keyframes??[],time)??base;}
export function evaluate2DProperty(tracks:Track[]|undefined,layerId:string,property:AnimatedProperty,time:number,base:number):number{const track=tracks?.find(t=>t.layerId===layerId&&t.property===property);return interpolate3DKeyframes(track?.keyframes??[],time)??base;}
function transform(mesh:Graphics3DMesh,tracks:Graphics3DTrack[]|undefined,time:number):Graphics3DMesh{const p=mesh.transform.position.map((v,i)=>evaluate3DProperty(tracks,"mesh",mesh.id,(["positionX","positionY","positionZ"] as const)[i],time,v)) as [number,number,number];const r=mesh.transform.rotation.map((v,i)=>evaluate3DProperty(tracks,"mesh",mesh.id,(["rotationX","rotationY","rotationZ"] as const)[i],time,v)) as [number,number,number];const s=mesh.transform.scale.map((v,i)=>evaluate3DProperty(tracks,"mesh",mesh.id,(["scaleX","scaleY","scaleZ"] as const)[i],time,v)) as [number,number,number];return{...mesh,transform:{position:p,rotation:r,scale:s}};}
function camera(camera:Graphics3DCamera,tracks:Graphics3DTrack[]|undefined,time:number):Graphics3DCamera{const p=camera.position.map((v,i)=>evaluate3DProperty(tracks,"camera",camera.id,(["positionX","positionY","positionZ"] as const)[i],time,v)) as [number,number,number];const r=camera.rotation.map((v,i)=>evaluate3DProperty(tracks,"camera",camera.id,(["rotationX","rotationY","rotationZ"] as const)[i],time,v)) as [number,number,number];return{...camera,position:p,rotation:r,fov:evaluate3DProperty(tracks,"camera",camera.id,"fov",time,camera.fov??50)};}
export function evaluate3DWorldAtTime(world:Graphics3DWorld,time:number):Graphics3DWorld{const tracks=world.timeline?.tracks;if(!tracks?.length)return world;return{...world,meshes:world.meshes.map(mesh=>transform(mesh,tracks,time)),cameras:world.cameras.map(c=>camera(c,tracks,time))};}
export function evaluate3DViewAtTime(view:Graphics3DView,timeline:SceneTimeline|undefined,time:number):Graphics3DView{const tracks=timeline?.tracks;return{...view,x:evaluate2DProperty(tracks,view.id,"x",time,view.x),y:evaluate2DProperty(tracks,view.id,"y",time,view.y),width:evaluate2DProperty(tracks,view.id,"width",time,view.width),height:evaluate2DProperty(tracks,view.id,"height",time,view.height),rotation:evaluate2DProperty(tracks,view.id,"rotation",time,view.rotation??0),opacity:evaluate2DProperty(tracks,view.id,"opacity",time,view.opacity??1)};}
