import * as THREE from "three";
import type { Graphics3DCamera, Graphics3DLight, Graphics3DMaterial, Graphics3DMesh, Graphics3DView, Graphics3DWorld } from "./types";
export interface Graphics3DRenderOptions { background?: string | number; pixelRatio?: number; width?: number; height?: number }
export interface Graphics3DRenderer { render(world:Graphics3DWorld,camera:Graphics3DCamera,view?:Pick<Graphics3DView,"visibility">,options?:Graphics3DRenderOptions):THREE.Scene; mount(container:HTMLElement):void; resize(width?:number,height?:number):void; getCanvas():HTMLCanvasElement|undefined; dispose():void }
function materialFor(material?:Graphics3DMaterial):THREE.MeshStandardMaterial { const value=material??{}; return new THREE.MeshStandardMaterial({color:value.color??"#ffffff",opacity:value.opacity??1,transparent:(value.opacity??1)<1,metalness:value.metalness??0,roughness:value.roughness??0.8,wireframe:value.wireframe??false}); }
export function createThreeGeometry(mesh:Graphics3DMesh):THREE.BufferGeometry { const geometry=new THREE.BufferGeometry(); geometry.setAttribute("position",new THREE.Float32BufferAttribute(mesh.geometry.vertices,3)); geometry.setIndex(mesh.geometry.indices); if(mesh.geometry.normals?.length)geometry.setAttribute("normal",new THREE.Float32BufferAttribute(mesh.geometry.normals,3));else geometry.computeVertexNormals(); if(mesh.geometry.uv?.length)geometry.setAttribute("uv",new THREE.Float32BufferAttribute(mesh.geometry.uv,2)); geometry.computeBoundingSphere(); return geometry; }
export function createThreeCamera(camera:Graphics3DCamera,aspect=1):THREE.Camera { const near=camera.near??0.1,far=camera.far??2000,[x,y,z]=camera.position,[rx,ry,rz]=camera.rotation; if(camera.projection==="orthographic"){const zoom=camera.zoom??1,halfHeight=5/zoom,halfWidth=halfHeight*aspect,result=new THREE.OrthographicCamera(-halfWidth,halfWidth,halfHeight,-halfHeight,near,far);result.position.set(x,y,z);result.rotation.set(rx,ry,rz);return result;} const result=new THREE.PerspectiveCamera(camera.fov??50,aspect,near,far);result.position.set(x,y,z);result.rotation.set(rx,ry,rz);return result; }
function visible(mesh:Graphics3DMesh,view?:Pick<Graphics3DView,"visibility">):boolean { const filter=view?.visibility;if(!filter||filter.mode==="all")return true;const included=filter.objects.includes(mesh.id);return filter.mode==="include"?included:!included; }
function addLight(scene:THREE.Scene,light:Graphics3DLight):void { const color=light.color??"#ffffff",intensity=light.intensity??1;let object:THREE.Light;switch(light.type){case"ambient":object=new THREE.AmbientLight(color,intensity);break;case"directional":object=new THREE.DirectionalLight(color,intensity);break;case"point":object=new THREE.PointLight(color,intensity,light.distance??0);break;case"spot":object=new THREE.SpotLight(color,intensity,light.distance??0,light.angle??Math.PI/3,light.penumbra??0);break;}if(light.position)object.position.set(...light.position);if(light.rotation)object.rotation.set(...light.rotation);scene.add(object); }
export function createThreeScene(world:Graphics3DWorld,view?:Pick<Graphics3DView,"visibility">):THREE.Scene { const scene=new THREE.Scene();for(const light of world.lights??[])addLight(scene,light);for(const mesh of world.meshes){if(!visible(mesh,view))continue;const object=new THREE.Mesh(createThreeGeometry(mesh),materialFor(mesh.material));object.name=mesh.name??mesh.id;object.userData.graphics3DId=mesh.id;object.position.set(...mesh.transform.position);object.rotation.set(...mesh.transform.rotation);object.scale.set(...mesh.transform.scale);scene.add(object);}return scene; }
export class ThreeGraphics3DRenderer implements Graphics3DRenderer { private renderer:THREE.WebGLRenderer|undefined;private container:HTMLElement|undefined;mount(container:HTMLElement):void{this.container=container;this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));this.resize();container.appendChild(this.renderer.domElement);}render(world:Graphics3DWorld,camera:Graphics3DCamera,view?:Pick<Graphics3DView,"visibility">,options?:Graphics3DRenderOptions):THREE.Scene{const scene=createThreeScene(world,view);if(options?.background!==undefined)scene.background=new THREE.Color(options.background);if(!this.renderer)return scene;const width=options?.width??this.container?.clientWidth??1,height=options?.height??this.container?.clientHeight??1;this.renderer.setPixelRatio(options?.pixelRatio??Math.min(window.devicePixelRatio||1,2));this.renderer.setSize(Math.max(1,width),Math.max(1,height),false);this.renderer.render(scene,createThreeCamera(camera,width/height));return scene;}resize(width=this.container?.clientWidth||1,height=this.container?.clientHeight||1):void{this.renderer?.setSize(Math.max(1,width),Math.max(1,height),false);}getCanvas():HTMLCanvasElement|undefined{return this.renderer?.domElement;}dispose():void{this.renderer?.dispose();this.renderer?.domElement.remove();this.renderer=undefined;this.container=undefined;} }
