import { describe,expect,it } from "vitest";
import { resolveOutput, resolveScene, resolveViewportComposition } from "./presentation";
import type { GraphicsDocument } from "./types";

const doc=():GraphicsDocument=>({width:1920,height:1080,layers:[{id:"bg",type:"rectangle",x:0,y:0,width:1920,height:1080,visible:true},{id:"logo",type:"3d-view",x:100,y:100,width:500,height:300,visible:true,view3dId:"view",viewportOverrides:{venue:{visible:false}}},{id:"name",type:"text",x:100,y:800,width:800,height:100,text:"Speaker",visible:true,viewportOverrides:{venue:{y:1400}}},{id:"lyrics",type:"text",x:100,y:900,width:1200,height:100,text:"Lyrics",visible:true,viewportOverrides:{broadcast:{visible:false}}}],compositions:[{id:"broadcast",name:"Broadcast",layerIds:["bg","logo","name","lyrics"]},{id:"venue",name:"Venue",layerIds:["bg","logo","name","lyrics"]}],viewports:[{id:"yt",name:"YouTube",width:1920,height:1080,compositionIds:["broadcast"]},{id:"led",name:"Venue LED",width:1080,height:1920,compositionIds:["venue"]}],timeline:{scenes:[{id:"intro",name:"Intro",compositionId:"broadcast",start:0,duration:5},{id:"talk",name:"Talk",compositionId:"broadcast",start:5,duration:20}],currentSceneId:"intro",currentTime:0,tracks:[]},worlds3d:[{id:"world",meshes:[],cameras:[{id:"cam",position:[0,0,5],rotation:[0,0,0],projection:"perspective"}],timeline:{tracks:[],duration:10,loop:true}}],views3d:[{id:"view",worldId:"world",cameraId:"cam",renderAssetId:"render",x:0,y:0,width:500,height:300,worldTime:{offset:1,rate:1,loop:true}}],outputs:[{id:"youtube",name:"YouTube",viewportId:"yt",playback:"live",background:"transparent"},{id:"venue",name:"Venue",viewportId:"led",playback:"live",background:"transparent"}]});

describe("WEGRA cross-layer integration",()=>{
 it("resolves world → view → layer",()=>{const d=doc();const l=d.layers.find(x=>x.view3dId==="view")!;const v=d.views3d!.find(x=>x.id===l.view3dId)!;expect(v.worldId).toBe("world");expect(d.worlds3d!.find(x=>x.id===v.worldId)?.timeline?.loop).toBe(true);});
 it("resolves composition → scene → viewport → output",()=>{const d=doc();const r=resolveOutput(d,"youtube",7)!;expect(r.viewport.id).toBe("yt");expect("scene" in r && r.scene.id).toBe("talk");expect("composition" in r && r.composition.id).toBe("broadcast");});
 it("allows the same composition model to feed different presentation contexts",()=>{const d=doc();expect(resolveViewportComposition(d,"yt")?.composition.id).toBe("broadcast");expect(resolveViewportComposition(d,"led")?.composition.id).toBe("venue");});
 it("keeps viewport-specific layer state isolated",()=>{const d=doc();const yt=resolveViewportComposition(d,"yt")!;const led=resolveViewportComposition(d,"led")!;expect(yt.layers.find(x=>x.id==="lyrics")?.visible).toBe(false);expect(led.layers.find(x=>x.id==="lyrics")?.visible).toBe(true);expect(led.layers.find(x=>x.id==="name")?.y).toBe(1400);});
 it("does not mutate the source graph during complete resolution",()=>{const d=doc();const before=JSON.stringify(d);resolveOutput(d,"youtube",7);resolveOutput(d,"venue",7);resolveScene(d,12,"led");expect(JSON.stringify(d)).toBe(before);});
 it("supports concurrent independent outputs",()=>{const d=doc();const a=resolveOutput(d,"youtube",7)!;const b=resolveOutput(d,"venue",7)!;expect(a.viewport.id).not.toBe(b.viewport.id);});
});
