import { useCallback, useEffect, useRef, useState } from "react";
import { GraphicsEditorCanvas, type DrawingPreview } from "./components/GraphicsEditorCanvas";
import { GraphicsEditorToolbar } from "./components/GraphicsEditorToolbar";
import { SceneTimelinePanel } from "./components/SceneTimeline";
import { LayerList } from "./components/LayerList";
import { LayerProperties } from "./components/properties/LayerProperties";
import { HEIGHT, KEYFRAMES, WIDTH } from "./constants";
import { orthogonalPoint, pathCommandsToD } from "./geometry";
import { useCanvasInteraction } from "./hooks/useCanvasInteraction";
import { useEditorHistory } from "./hooks/useEditorHistory";
import { useEditorKeyboard } from "./hooks/useEditorKeyboard";
import { useEditorSelection } from "./hooks/useEditorSelection";
import { useEditorTransaction } from "./hooks/useEditorTransaction";
import { useLayerOperations } from "./hooks/useLayerOperations";
import type { AnimatedProperty } from "./timeline";
import { createKeyframe, createScene, createTrack, interpolateKeyframes, timelineDuration, upsertKeyframe } from "./timeline";
import type { GraphicsEditorProps, GraphicsDocument, Layer, PathCommand, PathNode, SceneTimeline } from "./types";
const ANIMATED_PROPERTIES:AnimatedProperty[]=["x","y","width","height","rotation","opacity"];
function numericValue(layer:Layer,property:AnimatedProperty){if(property==="rotation")return Number(layer.rotation??0);if(property==="opacity")return Number(layer.style?.opacity??1);return Number(layer[property]);}
export function GraphicsEditor({document:initialDocument,assets=[],onChange}:GraphicsEditorProps){const{document,setDocument,undo,redo,canUndo,canRedo,resetHistory}=useEditorHistory(initialDocument);const{selectedIds,primaryId,select,clear}=useEditorSelection(document.layers[0]?.id??null);const[grid,setGrid]=useState(false),[safe,setSafe]=useState(false),[aspectLock,setAspectLock]=useState(true),[assetPicker,setAssetPicker]=useState(false);const[activeTool,setActiveTool]=useState<"select"|"line"|"path"|"orthogonal">("select");const[drawing,setDrawing]=useState<DrawingPreview|null>(null);const drawingRef=useRef<DrawingPreview|null>(null);const artboardRef=useRef<HTMLDivElement>(null);const[timeline,setTimeline]=useState<SceneTimeline>(()=>initialDocument.timeline??(()=>{const scene=createScene("Scene 1");return{scenes:[scene],currentSceneId:scene.id,currentTime:0,tracks:[]}})());const[playing,setPlaying]=useState(false);const lastFrame=useRef<number|null>(null);
useEffect(()=>{if(!playing)return;const tick=(now:number)=>{const last=lastFrame.current??now,dt=(now-last)/1000;lastFrame.current=now;const total=timelineDuration(timeline),next=timeline.currentTime+dt;if(next>=total){setPlaying(false);setTimeline(t=>({...t,currentTime:total}));lastFrame.current=null;return}setTimeline(t=>({...t,currentTime:next}));requestAnimationFrame(tick)};const id=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(id);lastFrame.current=null}},[playing]);useEffect(()=>{onChange?.({...document,timeline})},[document,timeline,onChange]);useEffect(()=>{if(initialDocument!==document)resetHistory(initialDocument)},[initialDocument,document,resetHistory]);const commit=useCallback((next:GraphicsDocument)=>setDocument(next,true),[setDocument]);const transientChange=useCallback((next:GraphicsDocument)=>setDocument(next,false),[setDocument]);const transaction=useEditorTransaction(commit);const{updateLayer,updateStyle,add,remove,duplicate,bringForward,sendBackward,bringToFront,sendToBack,group,ungroup}=useLayerOperations(setDocument);const interaction=useCanvasInteraction(document,artboardRef,grid,aspectLock,transientChange);useEditorKeyboard(undo,redo);
const animatedLayers=document.layers.map(layer=>{let next={...layer};for(const track of timeline.tracks.filter(t=>t.layerId===layer.id)){const value=interpolateKeyframes(track.keyframes,timeline.currentTime);if(value===undefined)continue;if(track.property==="opacity")next.style={...next.style,opacity:value};else if(track.property==="rotation")next.rotation=value;else(next as any)[track.property]=value}return next});const selectedLayer=animatedLayers.find(l=>l.id===primaryId)??null;const addLayer=(type:Parameters<typeof add>[0])=>{const id=add(type);select(id)};const deleteSelected=()=>{if(!selectedIds.size)return;remove(selectedIds);clear()};const duplicateSelected=()=>{if(!selectedIds.size)return;const ids=duplicate(selectedIds);if(ids.length)select(ids[0])};
const ensureTrackAndKey=(id:string,property:AnimatedProperty,value:number)=>setTimeline(t=>{const existing=t.tracks.find(x=>x.layerId===id&&x.property===property);const track=existing??createTrack(id,property);const nextTrack=upsertKeyframe(track,createKeyframe(t.currentTime,value));return{...t,tracks:existing?t.tracks.map(x=>x.id===track.id?nextTrack:x):[...t.tracks,nextTrack]}});const changeLayer=(id:string,patch:Partial<Layer>)=>{updateLayer(id,patch);for(const[property,value]of Object.entries(patch)){if(!ANIMATED_PROPERTIES.includes(property as AnimatedProperty))continue;const n=Number(value);if(Number.isFinite(n))ensureTrackAndKey(id,property as AnimatedProperty,n)}};const changeStyle=(id:string,key:string,value:string|number)=>{updateStyle(id,key,value);if(key==="opacity"){const n=Number(value);if(Number.isFinite(n))ensureTrackAndKey(id,"opacity",n)}};
const canvasPoint=(e:React.PointerEvent)=>{const r=artboardRef.current?.getBoundingClientRect();return r?{x:(e.clientX-r.left)*WIDTH/r.width,y:(e.clientY-r.top)*HEIGHT/r.height}:null};const finishDrawing=useCallback(()=>{const c=drawingRef.current;if(!c||c.points.length<2){drawingRef.current=null;setDrawing(null);return}const xs=c.points.map(p=>p.x),ys=c.points.map(p=>p.y),minX=Math.min(...xs),minY=Math.min(...ys),maxX=Math.max(...xs),maxY=Math.max(...ys),points=c.points.map(p=>({x:p.x-minX,y:p.y-minY})),nodes:PathNode[]=points.map(p=>({x:p.x,y:p.y,kind:"corner"})),pathCommands:PathCommand[]=nodes.map((p,i)=>i===0?{type:"M",x:p.x,y:p.y}:{type:"L",x:p.x,y:p.y}),id=`${c.tool}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,layer:Layer={id,type:c.tool==="line"?"line":"path" as "line"|"path",x:minX,y:minY,width:Math.max(1,maxX-minX),height:Math.max(1,maxY-minY),path:pathCommandsToD(pathCommands),pathCommands,...(c.tool==="line"?{}:{nodes}),style:{fill:"none",stroke:"#fff","stroke-width":4,"stroke-linecap":"round","stroke-linejoin":"round"}};commit({...document,layers:[...document.layers,layer]});select(id);drawingRef.current=null;setDrawing(null);setActiveTool("select")},[commit,document,select]);const onCanvasPointerDown=(e:React.PointerEvent)=>{if(activeTool==="select"){clear();return}const p=canvasPoint(e);if(!p)return;if(activeTool==="line"){drawingRef.current={tool:"line",points:[p]};setDrawing(drawingRef.current);return}const c=drawingRef.current;if(!c){drawingRef.current={tool:activeTool,points:[p]};setDrawing(drawingRef.current);return}const last=c.points[c.points.length-1],next=activeTool==="orthogonal"?orthogonalPoint(last.x,last.y,p.x,p.y,Math.abs(p.x-last.x)>=Math.abs(p.y-last.y)):p;drawingRef.current={...c,points:[...c.points,next]};setDrawing(drawingRef.current)};const onCanvasPointerMove=(e:React.PointerEvent)=>{if(drawingRef.current?.tool==="line"&&drawingRef.current.points.length===1){const p=canvasPoint(e);if(p)setDrawing({...drawingRef.current,points:[drawingRef.current.points[0],p]});return}interaction.pointerMove(e)};const onCanvasPointerUp=()=>{if(drawingRef.current?.tool==="line")finishDrawing();else interaction.pointerUp()};const onPointerDown=(e:React.PointerEvent,id:string,kind:string,handle?:string)=>{if(activeTool!=="select")return;if(kind==="move")select(id,e.shiftKey);transaction.begin(document);interaction.pointerDown(e,id,kind,handle)};const seek=(time:number)=>setTimeline(t=>({...t,currentTime:Math.max(0,Math.min(timelineDuration(t),time))}));const changeTimeline=(next:SceneTimeline)=>setTimeline(next);
return <div className="graphics-editor"><style>{KEYFRAMES}</style><GraphicsEditorToolbar grid={grid} safe={safe} canUndo={canUndo} canRedo={canRedo} onUndo={undo} onRedo={redo} onAdd={addLayer} onDuplicate={duplicateSelected} onDelete={deleteSelected} onToggleGrid={()=>setGrid(v=>!v)} onToggleSafe={()=>setSafe(v=>!v)} activeTool={activeTool} onTool={tool=>{setActiveTool(tool);drawingRef.current=null;setDrawing(null)}} onGroup={()=>{const id=group(selectedIds);if(id)select(id)}} onUngroup={()=>{if(primaryId)ungroup(primaryId)}} onForward={()=>selectedIds.forEach(bringForward)} onBackward={()=>selectedIds.forEach(sendBackward)} onFront={()=>selectedIds.forEach(bringToFront)} onBack={()=>selectedIds.forEach(sendToBack)} canGroup={selectedIds.size>=2} canUngroup={!!primaryId&&document.layers.some(l=>l.id===primaryId&&l.type==="group")}/><div className="ge-layout"><GraphicsEditorCanvas artboardRef={artboardRef} layers={animatedLayers} selectedIds={selectedIds} grid={grid} safe={safe} background={document.background??"#111"} onPointerMove={onCanvasPointerMove} onPointerUp={onCanvasPointerUp} onCanvasPointerDown={onCanvasPointerDown} onLayerPointerDown={onPointerDown} drawing={drawing} onDrawingDoubleClick={finishDrawing} onPathNodes={(id,nodes)=>updateLayer(id,{nodes,path:undefined})}/><aside className="ge-properties"><LayerList layers={document.layers} selectedIds={selectedIds} onSelect={id=>select(id)}/>{selectedLayer?<LayerProperties layer={selectedLayer} assets={assets} aspectLock={aspectLock} assetPicker={assetPicker} onLayer={changeLayer} onStyle={changeStyle} onChooseAsset={asset=>{updateLayer(selectedLayer.id,{src:asset.url});setAssetPicker(false)}} onToggleAssetPicker={()=>setAssetPicker(v=>!v)} onAspectLock={setAspectLock}/>:<div className="ge-section"><span>Select a layer.</span></div>}</aside></div><SceneTimelinePanel timeline={timeline} layers={document.layers} onChange={changeTimeline} onSeek={seek}/><div className="ge-playback"><button onClick={()=>seek(0)}>⏮</button><button onClick={()=>setPlaying(v=>!v)}>{playing?"⏸":"▶"}</button><span>{timeline.currentTime.toFixed(2)}s / {timelineDuration(timeline).toFixed(2)}s</span></div></div>;
}
export const defaultGraphicsDocument:GraphicsDocument={width:WIDTH,height:HEIGHT,background:"#111",layers:[{id:"title",type:"text",x:160,y:300,width:1600,height:180,text:"Hello graphics editor",style:{"font-size":"92px","font-weight":700,color:"#fff","text-align":"center"}}]};