import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { TransformControls } from "three/examples/jsm/controls/TransformControls.js";
import type { Graphics3DCamera, Graphics3DLight, Graphics3DMesh, Graphics3DWorld } from "./types";
import { createThreeGeometry } from "./3d-renderer";
import { createBoxMesh } from "./3d-primitives";

export interface ThreeDWorkspaceProps { world: Graphics3DWorld; onChange: (world: Graphics3DWorld) => void; className?: string; }
const DEFAULT_CAMERA: Graphics3DCamera = { id: "camera-main", name: "Main camera", position: [5, 4, 8], rotation: [0, 0, 0], projection: "perspective", fov: 50, near: 0.1, far: 2000 };
function makeCamera(camera: Graphics3DCamera, aspect: number): THREE.Camera { if (camera.projection === "orthographic") { const h=5/(camera.zoom??1),w=h*aspect,r=new THREE.OrthographicCamera(-w,w,h,-h,camera.near??0.1,camera.far??2000); r.position.set(...camera.position);r.rotation.set(...camera.rotation);return r; } const r=new THREE.PerspectiveCamera(camera.fov??50,aspect,camera.near??0.1,camera.far??2000);r.position.set(...camera.position);r.rotation.set(...camera.rotation);return r; }

export function ThreeDWorkspace({ world: inputWorld, onChange, className }: ThreeDWorkspaceProps) {
  const world=inputWorld.cameras.length?inputWorld:{...inputWorld,cameras:[DEFAULT_CAMERA]};
  const hostRef=useRef<HTMLDivElement>(null), objectsRef=useRef(new Map<string,THREE.Mesh>()), transformRef=useRef<TransformControls|null>(null), cameraRef=useRef<THREE.Camera|null>(null), worldRef=useRef(world), selectedRef=useRef<string|null>(null);
  worldRef.current=world;
  const [selectedId,setSelectedId]=useState<string|null>(world.meshes[0]?.id??null), [cameraId,setCameraId]=useState(world.cameras[0]?.id??DEFAULT_CAMERA.id), [mode,setMode]=useState<"translate"|"rotate"|"scale">("translate");
  selectedRef.current=selectedId;

  useEffect(()=>{ if(!hostRef.current)return; const host=hostRef.current,renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
    const scene=new THREE.Scene();scene.background=new THREE.Color("#15171b");scene.add(new THREE.GridHelper(20,20),new THREE.AxesHelper(2));scene.add(new THREE.AmbientLight("#ffffff",1.1));const key=new THREE.DirectionalLight("#ffffff",2);key.position.set(5,8,6);scene.add(key);
    const active=worldRef.current.cameras.find(c=>c.id===cameraId)??worldRef.current.cameras[0];if(!active){renderer.dispose();renderer.domElement.remove();return;}const camera=makeCamera(active,(host.clientWidth||800)/(host.clientHeight||520));cameraRef.current=camera;
    const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;const transform=new TransformControls(camera,renderer.domElement);transformRef.current=transform;scene.add(transform.getHelper());
    const sync=()=>{const current=worldRef.current;for(const mesh of current.meshes){let object=objectsRef.current.get(mesh.id);if(!object){object=new THREE.Mesh(createThreeGeometry(mesh),new THREE.MeshStandardMaterial({color:mesh.material?.color??"#78a9ff",roughness:mesh.material?.roughness??0.75,metalness:mesh.material?.metalness??0,wireframe:mesh.material?.wireframe??false}));object.name=mesh.name??mesh.id;object.userData.graphics3DId=mesh.id;scene.add(object);objectsRef.current.set(mesh.id,object);}object.position.set(...mesh.transform.position);object.rotation.set(...mesh.transform.rotation);object.scale.set(...mesh.transform.scale);}for(const[id,object]of objectsRef.current)if(!current.meshes.some(m=>m.id===id)){scene.remove(object);object.geometry.dispose();(object.material as THREE.Material).dispose();objectsRef.current.delete(id);}const selected=selectedRef.current?objectsRef.current.get(selectedRef.current):undefined;if(selected)transform.attach(selected);else transform.detach();};
    sync();
    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();const onPointerDown=(event:PointerEvent)=>{if(transform.dragging)return;const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects([...objectsRef.current.values()])[0];setSelectedId(hit?.object.userData.graphics3DId??null);};
    const onDrag=(event:{value:boolean})=>{orbit.enabled=!event.value;};const onObjectChange=()=>{const id=selectedRef.current,object=id?objectsRef.current.get(id):undefined,current=id?worldRef.current.meshes.find(m=>m.id===id):undefined;if(!object||!current)return;onChange(updateWorldMesh(worldRef.current,id,{transform:{position:object.position.toArray() as [number,number,number],rotation:object.rotation.toArray().slice(0,3) as [number,number,number],scale:object.scale.toArray() as [number,number,number]}}));};
    renderer.domElement.addEventListener("pointerdown",onPointerDown);transform.addEventListener("dragging-changed",onDrag);transform.addEventListener("objectChange",onObjectChange);
    const resize=()=>{const w=host.clientWidth||1,h=host.clientHeight||1;renderer.setSize(w,h,false);if(camera instanceof THREE.PerspectiveCamera)camera.aspect=w/h;camera.updateProjectionMatrix();};resize();window.addEventListener("resize",resize);let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);orbit.update();renderer.render(scene,camera);};animate();
    return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",resize);renderer.domElement.removeEventListener("pointerdown",onPointerDown);transform.removeEventListener("dragging-changed",onDrag);transform.removeEventListener("objectChange",onObjectChange);orbit.dispose();transform.dispose();transformRef.current=null;cameraRef.current=null;for(const object of objectsRef.current.values()){object.geometry.dispose();(object.material as THREE.Material).dispose();}objectsRef.current.clear();renderer.dispose();renderer.domElement.remove();};
  },[cameraId]);
  useEffect(()=>{transformRef.current?.setMode(mode);},[mode]);
  useEffect(()=>{const object=selectedId?objectsRef.current.get(selectedId):undefined;if(object)transformRef.current?.attach(object);else transformRef.current?.detach();},[selectedId]);
  useEffect(()=>{for(const mesh of world.meshes){const object=objectsRef.current.get(mesh.id);if(object){object.position.set(...mesh.transform.position);object.rotation.set(...mesh.transform.rotation);object.scale.set(...mesh.transform.scale);}}},[world.meshes]);

  const updateMesh=(id:string,patch:Partial<Omit<Graphics3DMesh,"id">>)=>onChange(updateWorldMesh(world,id,patch));const updateCamera=(id:string,patch:Partial<Omit<Graphics3DCamera,"id">>)=>onChange(updateWorldCamera(world,id,patch));const addBox=()=>{const id=`box-${Date.now()}`;onChange({...world,meshes:[...world.meshes,createBoxMesh(id,2,2,2,{position:[0,1,0],rotation:[0,0,0],scale:[1,1,1]})]});setSelectedId(id);};const deleteMesh=()=>{if(!selectedId)return;onChange({...world,meshes:world.meshes.filter(m=>m.id!==selectedId)});setSelectedId(null);};const addCamera=()=>{const id=`camera-${Date.now()}`;onChange({...world,cameras:[...world.cameras,{...DEFAULT_CAMERA,id,name:`Camera ${world.cameras.length+1}`}]});setCameraId(id);};const addLight=()=>{const light:Graphics3DLight={id:`light-${Date.now()}`,type:"directional",position:[4,6,4],intensity:2};onChange({...world,lights:[...(world.lights??[]),light]});};
  const selected=world.meshes.find(m=>m.id===selectedId),camera=world.cameras.find(c=>c.id===cameraId)??world.cameras[0];
  return <div className={className} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 260px",minHeight:520,background:"#101216",color:"#eee",border:"1px solid #30343b",borderRadius:8,overflow:"hidden"}}><div ref={hostRef} style={{minHeight:520,position:"relative"}}><div style={{position:"absolute",top:10,left:10,zIndex:2,display:"flex",gap:6}}><button onClick={()=>setMode("translate")}>Move</button><button onClick={()=>setMode("rotate")}>Rotate</button><button onClick={()=>setMode("scale")}>Scale</button></div></div><aside style={{padding:12,overflow:"auto",borderLeft:"1px solid #30343b",fontSize:13}}><strong>{world.name??"3D World"}</strong><div style={{marginTop:10,display:"flex",gap:6}}><button onClick={addBox}>+ Box</button><button onClick={deleteMesh} disabled={!selectedId}>Delete</button></div><h4>Objects</h4>{world.meshes.map(mesh=><button key={mesh.id} onClick={()=>setSelectedId(mesh.id)} style={{display:"block",width:"100%",textAlign:"left",marginBottom:4,fontWeight:mesh.id===selectedId?700:400}}>{mesh.name??mesh.id}</button>)}{selected&&<><h4>Transform</h4>{(["x","y","z"] as const).map((axis,i)=><label key={axis} style={{display:"block"}}>{axis.toUpperCase()} <input type="number" step="0.1" value={selected.transform.position[i]} onChange={e=>{const p=[...selected.transform.position] as [number,number,number];p[i]=Number(e.target.value);updateMesh(selected.id,{transform:{...selected.transform,position:p}});}}/></label>)}</>}<h4>Camera</h4><div><select value={camera?.id??""} onChange={e=>setCameraId(e.target.value)}>{world.cameras.map(c=><option key={c.id} value={c.id}>{c.name??c.id}</option>)}</select> <button onClick={addCamera}>+</button></div>{camera&&<><select value={camera.projection} onChange={e=>updateCamera(camera.id,{projection:e.target.value as Graphics3DCamera["projection"]})}><option value="perspective">Perspective</option><option value="orthographic">Orthographic</option></select>{(["x","y","z"] as const).map((axis,i)=><label key={axis} style={{display:"block"}}>Cam {axis.toUpperCase()} <input type="number" step="0.1" value={camera.position[i]} onChange={e=>{const p=[...camera.position] as [number,number,number];p[i]=Number(e.target.value);updateCamera(camera.id,{position:p});}}/></label>)}</>}<h4>Lights</h4><div>{(world.lights??[]).length} lights <button onClick={addLight}>+ Light</button></div></aside></div>;
}
function updateWorldMesh(world:Graphics3DWorld,id:string,patch:Partial<Omit<Graphics3DMesh,"id">>):Graphics3DWorld{return{...world,meshes:world.meshes.map(mesh=>mesh.id===id?{...mesh,...patch}:mesh)};}
function updateWorldCamera(world:Graphics3DWorld,id:string,patch:Partial<Omit<Graphics3DCamera,"id">>):Graphics3DWorld{return{...world,cameras:world.cameras.map(camera=>camera.id===id?{...camera,...patch}:camera)};}
