import type { AnimationKeyframe, AnimationTrack, AnimationValue, Easing, InterpolationOptions, LayerClip, Scene, SceneTimeline, SceneTransitionType } from "./types";
export type AnimatedProperty="x"|"y"|"width"|"height"|"rotation"|"opacity"|"scaleX"|"scaleY";
export interface Keyframe{id:string;time:number;value:number;easing?:Easing}
export interface Track{id:string;layerId:string;property:AnimatedProperty;keyframes:Keyframe[]}
export const DEFAULT_SCENE_DURATION=5;
const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export function createScene(name="Scene",start=0,duration=DEFAULT_SCENE_DURATION):Scene{return{id:id("scene"),name,start,duration:Math.max(.1,duration)}}
export function createTrack(layerId:string,property:AnimatedProperty):Track{return{id:id("track"),layerId,property,keyframes:[]}}
export function createKeyframe(time:number,value:number,easing:Easing="linear"):Keyframe{return{id:id("key"),time,value,easing}}
export function createClip(layerId:string,start=0,duration=DEFAULT_SCENE_DURATION):LayerClip{return{id:id("clip"),layerId,start,duration:Math.max(.1,duration)}}
export function timelineDuration(t:SceneTimeline){return t.scenes.reduce((m,s)=>Math.max(m,s.start+s.duration),0)}
export function normalizeScenes(scenes:Scene[]){let cursor=0;return scenes.map(s=>{const n={...s,start:cursor,duration:Math.max(.1,s.duration)};cursor+=n.duration;return n})}
export function addScene(t:SceneTimeline,name?:string):SceneTimeline{const start=timelineDuration(t),scene=createScene(name??`Scene ${t.scenes.length+1}`,start);return{...t,scenes:[...t.scenes,scene],currentSceneId:scene.id,currentTime:start}}
export function insertEmptyScene(t:SceneTimeline,index:number,duration=DEFAULT_SCENE_DURATION):SceneTimeline{const scenes=normalizeScenes(t.scenes);const i=Math.max(0,Math.min(index,scenes.length));const scene=createScene(`Scene ${i+1}`,0,duration);const next=[...scenes.slice(0,i),scene,...scenes.slice(i)];const normalized=normalizeScenes(next);const inserted=normalized[i];return{...t,scenes:normalized,currentSceneId:inserted.id,currentTime:inserted.start}}
export function duplicateScene(t:SceneTimeline,sceneId:string):SceneTimeline{const scenes=normalizeScenes(t.scenes);const index=scenes.findIndex(s=>s.id===sceneId);if(index<0)return t;const source=scenes[index],newScene={...source,id:id("scene"),name:`${source.name} Copy`,start:0};const nextScenes=normalizeScenes([...scenes.slice(0,index+1),newScene,...scenes.slice(index+1)]);const offset=newScene.start-source.start;const oldEnd=source.start+source.duration;const newEnd=newScene.start+newScene.duration;const tracks=t.tracks.map(track=>{const keys=track.keyframes.filter(k=>k.time>=source.start&&k.time<=oldEnd);return keys.length?{...track,id:id("track"),keyframes:keys.map(k=>({...k,id:id("key"),time:k.time+offset}))}:null}).filter(Boolean) as Track[];const clips=(t.clips??[]).flatMap(c=>{const a=Math.max(c.start,source.start),b=Math.min(c.start+c.duration,oldEnd);return b>a?[{...c,id:id("clip"),start:a+offset,duration:Math.min(b-a,newEnd-(a+offset))}]:[]});return{...t,scenes:nextScenes,tracks:[...t.tracks,...tracks],clips:[...(t.clips??[]),...clips],currentSceneId:newScene.id,currentTime:newScene.start}}
export function removeScene(t:SceneTimeline,id:string):SceneTimeline{if(t.scenes.length<=1)return t;const scenes=normalizeScenes(t.scenes.filter(s=>s.id!==id));const current=scenes.find(s=>s.id===t.currentSceneId)??scenes.at(-1)!;return{...t,scenes,currentSceneId:current.id,currentTime:current.start}}
export function setSceneDuration(t:SceneTimeline,id:string,duration:number):SceneTimeline{return{...t,scenes:normalizeScenes(t.scenes.map(s=>s.id===id?{...s,duration:Math.max(.1,duration)}:s))}}
export function sceneAtTime(t:SceneTimeline,time:number){return t.scenes.find(s=>time>=s.start&&time<s.start+s.duration)??t.scenes.at(-1)}
export function transitionType(t:SceneTransitionType|undefined){return t??"cut"}
export function setSceneTransition(t:SceneTimeline,id:string,type:SceneTransitionType,duration:number):SceneTimeline{return{...t,scenes:t.scenes.map(s=>s.id===id?{...s,transition:{type,duration:Math.max(0,Math.min(duration,s.duration))}}:s)}}
export function setClip(t:SceneTimeline,clip:LayerClip):SceneTimeline{return{...t,clips:[...(t.clips??[]).filter(c=>c.id!==clip.id),clip]}}
export function removeClip(t:SceneTimeline,id:string):SceneTimeline{return{...t,clips:(t.clips??[]).filter(c=>c.id!==id)}}
export function moveClip(t:SceneTimeline,id:string,start:number):SceneTimeline{return{...t,clips:(t.clips??[]).map(c=>c.id===id?{...c,start:Math.max(0,start)}:c)}}
export function resizeClip(t:SceneTimeline,id:string,start:number,duration:number):SceneTimeline{return{...t,clips:(t.clips??[]).map(c=>c.id===id?{...c,start:Math.max(0,start),duration:Math.max(.1,duration)}:c)}}
export function clipAtTime(t:SceneTimeline,layerId:string,time:number){return(t.clips??[]).find(c=>c.layerId===layerId&&time>=c.start&&time<c.start+c.duration)}
export function duplicateTimelineRange(t:SceneTimeline,start:number,end:number,at=end):SceneTimeline{const lo=Math.min(start,end),hi=Math.max(start,end),duration=hi-lo;if(duration<=0)return t;const shift=at-lo;const stamp=Date.now();const tracks=t.tracks.map(track=>{const keys=track.keyframes.filter(k=>k.time>=lo&&k.time<=hi);if(!keys.length)return null;return{...track,id:`track-${stamp}-${Math.random().toString(36).slice(2,6)}`,keyframes:keys.map(k=>({...k,id:`key-${stamp}-${Math.random().toString(36).slice(2,6)}`,time:k.time+shift}))}}).filter(Boolean) as Track[];const clips=(t.clips??[]).flatMap(c=>{const a=Math.max(c.start,lo),b=Math.min(c.start+c.duration,hi);return b>a?[{...c,id:`clip-${stamp}-${Math.random().toString(36).slice(2,6)}`,start:a+shift,duration:b-a}]:[]});return{...t,tracks:[...t.tracks,...tracks],clips:[...(t.clips??[]),...clips]}}
export function duplicateTimeline(t:SceneTimeline,at=timelineDuration(t)):SceneTimeline{return duplicateTimelineRange(t,0,timelineDuration(t),at)}
export function setLoop(t:SceneTimeline,loop:boolean):SceneTimeline{return{...t,loop}}
function easing(x:number,o?:InterpolationOptions):number{const e=o?.easing?.mode??"linear";if(o?.mode==="discrete"||e==="step-start")return x<1?0:1;if(e==="step-end")return x<1?0:1;if(e==="ease-in")return x*x;if(e==="ease-out")return 1-(1-x)*(1-x);if(e==="ease-in-out")return x<.5?2*x*x:1-2*(1-x)*(1-x);if(e==="cubic-bezier"&&o?.easing?.bezier){const [x1,y1,x2,y2]=o.easing.bezier;let lo=0,hi=1;for(let i=0;i<24;i++){const u=(lo+hi)/2;const q=1-u;const bx=3*q*q*u*x1+3*q*u*u*x2+u*u*u;if(bx<x)lo=u;else hi=u}const u=(lo+hi)/2,q=1-u;return 3*q*q*u*y1+3*q*u*u*y2+u*u*u}return x}
function isTuple(v:AnimationValue):v is number[]{return Array.isArray(v)}
function colorParts(v:string){const m=v.trim().match(/^#([0-9a-f]{6}|[0-9a-f]{8})$/i);if(!m)return null;const h=m[1];return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),h.length===8?parseInt(h.slice(6,8),16):255]}
function interpolateValue(a:AnimationValue,b:AnimationValue,x:number,o?:InterpolationOptions):AnimationValue{if(o?.mode==="discrete")return x<1?a:b;if(typeof a==="number"&&typeof b==="number")return a+(b-a)x;if(isTuple(a)&&isTuple(b)&&a.length===b.length)return a.map((v,i)=>v+(b[i]-v)*x);if(typeof a==="string"&&typeof b==="string"){const ca=colorParts(a),cb=colorParts(b);if(ca&&cb){const c=ca.map((v,i)=>Math.round(v+(cb[i]-v)*x));return`#${c.map(v=>v.toString(16).padStart(2,"0")).join("")}`}return x<1?a:b}if(typeof a==="boolean"&&typeof b==="boolean")return x<1?a:b;return x<1?a:b}
export function interpolateAnimationKeyframes(k:AnimationKeyframe[],time:number){if(!k.length)return undefined;const a=[...k].sort((x,y)=>x.time-y.time);if(time<=a[0].time)return a[0].value;if(time>=a.at(-1)!.time)return a.at(-1)!.value;for(let i=1;i<a.length;i++)if(time<=a[i].time){const p=a[i],prev=a[i-1],x=easing((time-prev.time)/(p.time-prev.time),prev.interpolation);return interpolateValue(prev.value,p.value,x,prev.interpolation)}}
export function interpolateKeyframes(k:Keyframe[],time:number){return interpolateAnimationKeyframes(k.map(x=>({id:x.id,time:x.time,value:x.value,interpolation:x.easing?{easing:{mode:x.easing}}:undefined})),time) as number|undefined}
export function upsertKeyframe(t:Track,k:Keyframe):Track{return{...t,keyframes:[...t.keyframes.filter(x=>x.id!==k.id&&Math.abs(x.time-k.time)>.0001),k].sort((a,b)=>a.time-b.time)}}
export function moveKeyframe(t:Track,id:string,time:number):Track{const k=t.keyframes.find(x=>x.id===id);return k?upsertKeyframe(t,{...k,time:Math.max(0,time)}):t}
export function removeKeyframe(t:Track,id:string):Track{return{...t,keyframes:t.keyframes.filter(k=>k.id!==id)}}
