import type { FC } from "react";
import { defaultGradient } from "../../gradient";
import type { Gradient, GradientStop } from "../../types";

export const GradientProperties: FC<{ gradient?: Gradient; onGradient: (gradient: Gradient | undefined) => void }> = ({ gradient, onGradient }) => {
 const setG=(patch:Partial<Gradient>)=>onGradient({...defaultGradient(),...gradient,...patch,stops:gradient?.stops??defaultGradient().stops});
 const setStop=(i:number,patch:Partial<GradientStop>)=>onGradient({...gradient!,stops:gradient!.stops.map((s,n)=>n===i?{...s,...patch}:s)});
 return <div className="ge-section"><label>Gradient type<select value={gradient?.type??"none"} onChange={e=>e.target.value==="none"?onGradient(undefined):setG({type:e.target.value as Gradient["type"]})}><option value="none">None</option><option value="linear">Linear</option><option value="radial">Circular / radial</option></select></label>{gradient&&<>{gradient.type==="linear"?<label>Angle<input type="number" value={gradient.angle??90} min="0" max="360" onChange={e=>setG({angle:Number(e.target.value)})}/></label>:<div className="ge-two"><label>Center X<input type="number" value={gradient.cx??50} min="0" max="100" onChange={e=>setG({cx:Number(e.target.value)})}/></label><label>Center Y<input type="number" value={gradient.cy??50} min="0" max="100" onChange={e=>setG({cy:Number(e.target.value)})}/></label></div>}<div><b>Stops</b>{gradient.stops.map((s,i)=><div className="ge-two" key={i}><input type="color" value={s.color} onChange={e=>setStop(i,{color:e.target.value})}/><input type="number" min="0" max="100" value={Math.round(s.offset*100)} onChange={e=>setStop(i,{offset:Number(e.target.value)/100})}/><input type="number" min="0" max="100" value={Math.round((s.opacity??1)*100)} onChange={e=>setStop(i,{opacity:Number(e.target.value)/100})}/>{gradient.stops.length>2&&<button type="button" onClick={()=>onGradient({...gradient,stops:gradient.stops.filter((_,n)=>n!==i)})}>×</button>}</div>)}<button type="button" onClick={()=>onGradient({...gradient,stops:[...gradient.stops,{offset:.5,color:"#808080",opacity:1}]})}>+ Stop</button></div></>}</div>;
};
