import { useState, type FC } from "react";
import type { AnimationTrack, Composition, Layer } from "../types";
import { TimelineKeyMarkers } from "./timeline/TimelineKeyMarkers";
import { TimelineTrackRow } from "./timeline/TimelineTrackRow";
import { TimelineKeyframeEditor } from "./timeline/TimelineKeyframeEditor";
import { moveKeyframe, removeKeyframe, createKeyframe } from "../timeline";
export const CompositionTimelinePanel: FC<{composition:Composition;layers:Layer[];currentTime:number;onSeek:(time:number)=>void;onChange:(composition:Composition)=>void}> = ({composition,layers,currentTime,onSeek,onChange}) => {
 const total=Math.max(1,composition.duration ?? 10); const [selected,setSelected]=useState<{trackId:string;keyId:string}|null>(null); const tracks=composition.timeline?.tracks ?? [];
 const update=(next:AnimationTrack[])=>onChange({...composition,timeline:{tracks:next}});
 const add=(layer:Layer,property:string)=>{if(tracks.some(t=>t.targetId===layer.id&&t.property===property))return; const value=Number((layer as unknown as Record<string,unknown>)[property] ?? (property==="opacity"?layer.opacity:0))||0; update([...tracks,{id:"track-"+Date.now(),targetId:layer.id,property,keyframes:[createKeyframe(currentTime,value)]}]);};
 return <section className="ge-timeline" aria-label="Composition timeline"><div className="ge-timeline-subhead">{composition.name} timeline · {currentTime.toFixed(2)}s / {total.toFixed(2)}s</div><div className="ge-timeline-body" onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek(Math.max(0,Math.min(total,(e.clientX-r.left)/r.width*total)));}}><div className="ge-track-list">{layers.filter(l=>l.type!=="group").map(layer=><div key={layer.id} className="ge-tree-object"><b>{layer.name??layer.text??layer.id}</b>{["x","y","width","height","rotation","opacity"].map(property=>{const t=tracks.find(x=>x.targetId===layer.id&&x.property===property);return <TimelineTrackRow key={property} label={property} keyframeCount={t?.keyframes.length??0} onAdd={()=>add(layer,property)}>{t&&<div className="ge-track-key-area"><TimelineKeyMarkers keyframes={t.keyframes} total={total} selectedKeyId={selected?.keyId} onSelect={keyId=>setSelected({trackId:t.id,keyId})} onMove={(keyId,time)=>update(tracks.map(x=>x.id===t.id?moveKeyframe(x,keyId,time):x))} onDelete={keyId=>update(tracks.map(x=>x.id===t.id?removeKeyframe(x,keyId):x))}/></div>}</TimelineTrackRow>})}</div>)}</div></div>{selected&&(()=>{const t=tracks.find(x=>x.id===selected.trackId);const k=t?.keyframes.find(x=>x.id===selected.keyId);return t&&k?<TimelineKeyframeEditor value={k} onTimeChange={time=>update(tracks.map(x=>x.id===t.id?moveKeyframe(x,k.id,time):x))} onValueChange={value=>update(tracks.map(x=>x.id===t.id?{...x,keyframes:x.keyframes.map(y=>y.id===k.id?{...y,value}:y)}:x))} onEasingChange={easing=>update(tracks.map(x=>x.id===t.id?{...x,keyframes:x.keyframes.map(y=>y.id===k.id?{...y,interpolation:easing}:y)}:x))} onDelete={()=>update(tracks.map(x=>x.id===t.id?removeKeyframe(x,k.id):x))}/>:null})()}</section>; };