import type { FC } from "react";
import type { AlignMode, AlignReference, DistributeMode } from "../alignment";
import type { LayerType } from "../types";
export const GraphicsEditorToolbar: FC<{ grid:boolean; safe:boolean; canUndo:boolean; canRedo:boolean; onUndo:()=>void; onRedo:()=>void; onAdd:(type:LayerType)=>void; onDuplicate:()=>void; onDelete:()=>void; onToggleGrid:()=>void; onToggleSafe:()=>void; onTool:(tool:"select"|"line"|"path"|"orthogonal")=>void; activeTool:"select"|"line"|"path"|"orthogonal"; onGroup:()=>void; onUngroup:()=>void; onForward:()=>void; onBackward:()=>void; onFront:()=>void; onBack:()=>void; canGroup:boolean; canUngroup:boolean; onAlign:(mode:AlignMode,reference:AlignReference)=>void; onDistribute:(mode:DistributeMode)=>void; canAlign:boolean; canDistribute:boolean; }> = p => <div className="ge-toolbar" aria-label="Graphic tools">
<button onClick={p.onUndo} disabled={!p.canUndo}>↶ Undo</button><button onClick={p.onRedo} disabled={!p.canRedo}>↷ Redo</button><span className="ge-spacer"/>
<button className={p.activeTool==="select"?"ge-active":""} onClick={()=>p.onTool("select")}>↖ Select</button><button className={p.activeTool==="line"?"ge-active":""} onClick={()=>p.onTool("line")}>╱ Line</button><button className={p.activeTool==="path"?"ge-active":""} onClick={()=>p.onTool("path")}>⌁ Path</button><button className={p.activeTool==="orthogonal"?"ge-active":""} onClick={()=>p.onTool("orthogonal")}>⌞ Orthogonal</button><span className="ge-spacer"/>
<button onClick={p.onBackward}>↓ Back</button><button onClick={p.onForward}>↑ Forward</button><button onClick={p.onBack}>⇊ Backmost</button><button onClick={p.onFront}>⇈ Frontmost</button><button onClick={p.onGroup} disabled={!p.canGroup}>Group</button><button onClick={p.onUngroup} disabled={!p.canUngroup}>Ungroup</button><span className="ge-spacer"/>
<button disabled={!p.canAlign} onClick={()=>p.onAlign("left","selection")}>Align L</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("center-x","selection")}>Center X</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("right","selection")}>Align R</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("top","selection")}>Align T</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("center-y","selection")}>Center Y</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("bottom","selection")}>Align B</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("left","canvas")}>Canvas L</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("center-x","canvas")}>Canvas X</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("center-y","canvas")}>Canvas Y</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("right","canvas")}>Canvas R</button><button disabled={!p.canAlign} onClick={()=>p.onAlign("bottom","canvas")}>Canvas B</button><button disabled={!p.canDistribute} onClick={()=>p.onDistribute("horizontal")}>Distribute H</button><button disabled={!p.canDistribute} onClick={()=>p.onDistribute("vertical")}>Distribute V</button><span className="ge-spacer"/>
<button onClick={()=>p.onAdd("text")}>＋ Text</button><button onClick={()=>p.onAdd("rectangle")}>＋ Rectangle</button><button onClick={()=>p.onAdd("ellipse")}>＋ Ellipse</button><button onClick={()=>p.onAdd("image")}>＋ Image</button><button onClick={p.onDuplicate}>Duplicate</button><button onClick={p.onDelete}>Delete</button><button className={p.grid?"ge-active":""} onClick={p.onToggleGrid}>Grid</button><button className={p.safe?"ge-active":""} onClick={p.onToggleSafe}>Safe area</button>
</div>;
