import type { FC } from "react";
import type { AnimatedProperty, Keyframe, Layer } from "../types";
import type { SceneTimeline as Timeline } from "../types";
import { createKeyframe, createTrack, timelineDuration, upsertKeyframe, moveKeyframe, removeKeyframe } from "../timeline";
const PROPERTIES:AnimatedProperty[]=["x","y","width","height","rotation","opacity"];
export const SceneTimelinePanel:FC<{timeline:Timeline;layers:Layer[];onChange:(timeline:Timeline)=>void;onSeek:(time:number)=>void}> = ({timeline,layers,onChange,onSeek})=>{
 const total=Math.max(1,timelineDuration(timeline)); const toTime=(clientX:number,r:DOMRect)=>Math.max(0,Math.min(total,(clientX-r.left)/r.width*total));
 const addTrack=(layerId:string,property:AnimatedProperty)=>{if(timeline.tracks.some(t=>t.layerId===layerId&&t.property===property))return;onChange({...timeline,tracks:[...timeline.tracks,createTrack(layerId,property)]})};
 const addKey=(layer:Layer,property:AnimatedProperty)=>{const t=timeline.tracks.find(x=>x.layerId===layer.id&&x.property===property);if(!t)return;const value=property==="rotation"?(layer.rotation??0):property==="opacity"?Number(layer.style?.opacity??1):Number(layer[property]);const scene=timeline.scenes.find(s=>timeline.currentTime>=s.start&&timeline.currentTime<=s.start+s.duration)??timeline.scenes[0];const time=Math.max(scene.start,Math.min(timeline.currentTime,scene.start+scene.duration));onChange({...timeline,tracks:timeline.tracks.map(x=>x.id===t.id?upsertKeyframe(x,createKeyframe(time,value)):x)})};
 const updateKey=(trackId:string,keyId:string,time:number)=>onChange({...timeline,tracks:timeline.tracks.map(t=>t.id===trackId?moveKeyframe(t,keyId,time):t)});
 const deleteKey=(trackId:string,keyId:string)=>onChange({...timeline,tracks:timeline.tracks.map(t=>t.id===trackId?removeKeyframe(t,keyId):t)});
 return <section className="ge-timeline" aria-label="Scene timeline"><div className="ge-timeline-head"><b>Timeline</b><button onClick={()=>onSeek(Math.max(0,timeline.currentTime-.5))}>◀</button><button onClick={()=>onSeek(Math.min(total,timeline.currentTime+.5))}>▶</button><button onClick={()=>onSeek(0)}>● 0</button><span>{timeline.currentTime.toFixed(2)}s / {total.toFixed(2)}s</span></div>
 <div className="ge-timeline-ruler" style={{gridTemplateColumns:`repeat(${Math.max(1,Math.ceil(total))},1fr)`}}>{Array.from({length:Math.ceil(total)+1},(_,i)=><span key={i}>{i}s</span>)}</div>
 <div className="ge-timeline-body" onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek(toTime(e.clientX,r));}}>{timeline.scenes.map(s=><div key={s.id} className="ge-scene" style={{left:`${s.start/total*100}%`,width:`${s.duration/total*100}%`}}>{s.name}</div>)}{timeline.tracks.map(t=>t.keyframes.map(k=><button key={k.id} className="ge-key" style={{left:`${k.time/total*100}%`}} onPointerDown={e=>{e.stopPropagation();const body=e.currentTarget.parentElement!.getBoundingClientRect();const move=(ev:PointerEvent)=>updateKey(t.id,k.id,toTime(ev.clientX,body));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}} onDoubleClick={()=>deleteKey(t.id,k.id)} title={`${t.property}: ${k.value} — double-click to delete`}>◆</button>))}</div>
 <div className="ge-track-list">{layers.filter(l=>l.type!=="group").map(layer=><div className="ge-track-row" key={layer.id}><b>{layer.text||layer.id}</b>{PROPERTIES.map(p=>{const t=timeline.tracks.find(x=>x.layerId===layer.id&&x.property===p);return <button key={p} onClick={()=>t?addKey(layer,p):addTrack(layer.id,p)}>{p}{t?` · ${t.keyframes.length}`:" +"}</button>})}</div>)}</div><div className="ge-playhead" style={{left:`${Math.min(100,timeline.currentTime/total*100)}%`}} /></section>;
};
