import { useState, type FC } from "react";
import type { AnimatedProperty, Layer, SceneTransitionType } from "../types";
import type { SceneTimeline as Timeline } from "../types";
import { createClip, createKeyframe, createTrack, timelineDuration, upsertKeyframe, moveKeyframe, removeKeyframe, setClip, removeClip, resizeClip, moveClip, setSceneTransition } from "../timeline";
const PROPERTIES:AnimatedProperty[]=["x","y","width","height","rotation","opacity"];
const TRANSITIONS:SceneTransitionType[]=["cut","fade","dissolve","slide-left","slide-right","slide-up","slide-down"];
export const SceneTimelinePanel:FC<{timeline:Timeline;layers:Layer[];onChange:(timeline:Timeline)=>void;onSeek:(time:number)=>void}> = ({timeline,layers,onChange,onSeek})=>{
 const [selectedKey,setSelectedKey]=useState<{trackId:string;keyId:string}|null>(null); const total=Math.max(1,timelineDuration(timeline)); const toTime=(clientX:number,r:DOMRect)=>Math.max(0,Math.min(total,(clientX-r.left)/r.width*total));
 const addTrack=(layerId:string,property:AnimatedProperty)=>{if(timeline.tracks.some(t=>t.layerId===layerId&&t.property===property))return;onChange({...timeline,tracks:[...timeline.tracks,createTrack(layerId,property)]})};
 const addKey=(layer:Layer,property:AnimatedProperty)=>{const t=timeline.tracks.find(x=>x.layerId===layer.id&&x.property===property);if(!t)return;const value=property==="rotation"?(layer.rotation??0):property==="opacity"?Number(layer.style?.opacity??1):Number(layer[property]);const scene=timeline.scenes.find(s=>timeline.currentTime>=s.start&&timeline.currentTime<=s.start+s.duration)??timeline.scenes[0];const time=Math.max(scene.start,Math.min(timeline.currentTime,scene.start+scene.duration));const key=createKeyframe(time,value);onChange({...timeline,tracks:timeline.tracks.map(x=>x.id===t.id?upsertKeyframe(x,key):x)});setSelectedKey({trackId:t.id,keyId:key.id});};
 const updateKey=(trackId:string,keyId:string,time:number)=>onChange({...timeline,tracks:timeline.tracks.map(t=>t.id===trackId?moveKeyframe(t,keyId,time):t)});
 const deleteKey=(trackId:string,keyId:string)=>{onChange({...timeline,tracks:timeline.tracks.map(t=>t.id===trackId?removeKeyframe(t,keyId):t)});if(selectedKey?.keyId===keyId)setSelectedKey(null)};
 const patchKey=(trackId:string,keyId:string,patch:Partial<{value:number;easing:"linear"|"ease-in"|"ease-out"|"ease-in-out"}>)=>onChange({...timeline,tracks:timeline.tracks.map(t=>t.id===trackId?{...t,keyframes:t.keyframes.map(k=>k.id===keyId?{...k,...patch}:k)}:t)});
 const selected=selectedKey?timeline.tracks.find(t=>t.id===selectedKey.trackId)?.keyframes.find(k=>k.id===selectedKey.keyId):undefined;
 const addClip=(layerId:string)=>onChange(setClip(timeline,createClip(layerId,0,total))); const clipFor=(layerId:string)=>timeline.clips?.find(c=>c.layerId===layerId); const updateClip=(id:string,start:number,duration:number)=>onChange(resizeClip(timeline,id,start,duration));
 return <section className="ge-timeline" aria-label="Scene timeline"><div className="ge-timeline-head"><b>Timeline</b><button onClick={()=>onSeek(Math.max(0,timeline.currentTime-.5))}>◀</button><button onClick={()=>onSeek(Math.min(total,timeline.currentTime+.5))}>▶</button><button onClick={()=>onSeek(0)}>● 0</button><span>{timeline.currentTime.toFixed(2)}s / {total.toFixed(2)}s</span></div>
 <div className="ge-timeline-ruler" style={{gridTemplateColumns:`repeat(${Math.max(1,Math.ceil(total))},1fr)`}}>{Array.from({length:Math.ceil(total)+1},(_,i)=><span key={i}>{i}s</span>)}</div>
 <div className="ge-timeline-body" onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek(toTime(e.clientX,r));}}>{timeline.scenes.map(s=><div key={s.id} className="ge-scene" style={{left:`${s.start/total*100}%`,width:`${s.duration/total*100}%`}}>{s.name}</div>)}{timeline.tracks.map(t=>t.keyframes.map(k=><button key={k.id} className={selectedKey?.keyId===k.id?"ge-key ge-key-selected":"ge-key"} style={{left:`${k.time/total*100}%`}} onPointerDown={e=>{e.stopPropagation();setSelectedKey({trackId:t.id,keyId:k.id});const body=e.currentTarget.parentElement!.getBoundingClientRect();const move=(ev:PointerEvent)=>updateKey(t.id,k.id,toTime(ev.clientX,body));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}} onDoubleClick={()=>deleteKey(t.id,k.id)} title={`${t.property}: ${k.value} — double-click to delete`}>◆</button>))}</div>
 <div className="ge-track-list"><div className="ge-timeline-subhead">Layers & clips</div>{layers.filter(l=>l.type!=="group").map(layer=>{const clip=clipFor(layer.id);return <div className="ge-track-row" key={layer.id}><b>{layer.text||layer.id}</b><div className="ge-clip-cell">{clip?<div className="ge-clip" style={{left:`${clip.start/total*100}%`,width:`${clip.duration/total*100}%`}}><span>clip</span><button title="Move clip left" onClick={()=>onChange(moveClip(timeline,clip.id,Math.max(0,clip.start-.25)))}>◀</button><button title="Move clip right" onClick={()=>onChange(moveClip(timeline,clip.id,Math.min(total-clip.duration,clip.start+.25)))}>▶</button><input aria-label="Clip start" type="number" step=".1" value={clip.start} onChange={e=>updateClip(clip.id,Number(e.target.value)||0,clip.duration)}/><input aria-label="Clip duration" type="number" min=".1" step=".1" value={clip.duration} onChange={e=>updateClip(clip.id,clip.start,Number(e.target.value)||.1)}/><button onClick={()=>onChange(removeClip(timeline,clip.id))}>×</button></div>:<button onClick={()=>addClip(layer.id)}>+ clip</button>}</div>{PROPERTIES.map(p=>{const t=timeline.tracks.find(x=>x.layerId===layer.id&&x.property===p);return <button key={p} onClick={()=>t?addKey(layer,p):addTrack(layer.id,p)}>{p}{t?` · ${t.keyframes.length}`:" +"}</button>})}</div>})}</div>
 <div className="ge-scene-controls"><b>Scene transitions</b>{timeline.scenes.map((scene,i)=><div className="ge-scene-control" key={scene.id}><span>{scene.name}{i===timeline.scenes.length-1?"":" →"}</span>{i<timeline.scenes.length-1&&<><select value={scene.transition?.type??"cut"} onChange={e=>onChange(setSceneTransition(timeline,scene.id,e.target.value as SceneTransitionType,scene.transition?.duration??.5))}>{TRANSITIONS.map(t=><option key={t} value={t}>{t}</option>)}</select><input type="number" min="0" max={scene.duration} step=".1" value={scene.transition?.duration??0} onChange={e=>onChange(setSceneTransition(timeline,scene.id,scene.transition?.type??"cut",Number(e.target.value)||0))}/><span>s</span></>}</div>)}</div>
 {selected&&selectedKey&&<div className="ge-key-editor"><b>Keyframe</b><label>Time<input type="number" min="0" step="0.01" value={selected.time} onChange={e=>updateKey(selectedKey.trackId,selected.id,Number(e.target.value)||0)}/></label><label>Value<input type="number" step="0.01" value={selected.value} onChange={e=>patchKey(selectedKey.trackId,selected.id,{value:Number(e.target.value)||0})}/></label><label>Easing<select value={selected.easing??"linear"} onChange={e=>patchKey(selectedKey.trackId,selected.id,{easing:e.target.value as "linear"|"ease-in"|"ease-out"|"ease-in-out"})}><option value="linear">Linear</option><option value="ease-in">Ease in</option><option value="ease-out">Ease out</option><option value="ease-in-out">Ease in/out</option></select></label><button onClick={()=>deleteKey(selectedKey.trackId,selected.id)}>Delete keyframe</button></div>}
 <div className="ge-playhead" style={{left:`${Math.min(100,timeline.currentTime/total*100)}%`}} /></section>;
};