import * as THREE from "three";
import { TransformControls } from "three/examples/jsm/controls/TransformControls.js";
import type { Graphics3DMesh } from "../types";
import { extrudeFace, faceVertexIndices } from "../3d-mesh-operations";
import { bevelEdges, edgeKey, insetFace, meshEdges, type MeshEdge } from "../3d-mesh-topology";

export type MeshEditMode = "object" | "vertices" | "edges" | "faces";
export type FaceEditAction = "translate" | "extrude" | "inset" | "bevel";
export interface ThreeDMeshEditController { setMesh:(mesh:THREE.Mesh|undefined,data:Graphics3DMesh|undefined)=>void;updateData:(data:Graphics3DMesh|undefined)=>void;setMode:(mode:MeshEditMode)=>void;setFaceAction:(action:FaceEditAction)=>void;extrudeSelectedFace:(distance:number)=>void;insetSelectedFace:(amount:number)=>void;bevelSelectedEdges:(amount:number)=>void;dispose:()=>void }

export function createThreeDMeshEditController(scene:THREE.Scene,camera:THREE.Camera,renderer:THREE.WebGLRenderer,onChange:(geometry:Graphics3DMesh["geometry"])=>void):ThreeDMeshEditController{
 const handles=new THREE.Group();scene.add(handles);const transform=new TransformControls(camera,renderer.domElement);scene.add(transform.getHelper());const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let mesh:THREE.Mesh|undefined,data:Graphics3DMesh|undefined,mode:MeshEditMode="object",selectedVertices=new Set<number>(),selectedFaces=new Set<number>(),selectedEdges=new Set<string>(),dragSnapshot:number[]|null=null;
 const clear=()=>{while(handles.children.length){const o=handles.children.pop()!;o.traverse(x=>{const m=x as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(Array.isArray(m.material))m.material.forEach(y=>y.dispose());else if(m.material)(m.material as THREE.Material).dispose()})}};
 const removePivot=()=>{const p=handles.userData.pivot as THREE.Object3D|undefined;if(p){scene.remove(p);handles.userData.pivot=undefined}};
 const pivot=(p:THREE.Vector3)=>{removePivot();const g=new THREE.Group();g.position.copy(p);handles.userData.pivot=g;scene.add(g);transform.attach(g)};
 const rebuild=()=>{clear();removePivot();if(!mesh||!data)return;if(mode==="vertices"){for(let i=0;i<data.geometry.vertices.length/3;i++){const h=new THREE.Mesh(new THREE.SphereGeometry(.075,10,6),new THREE.MeshBasicMaterial({color:selectedVertices.has(i)?"#ffcc00":"#fff"}));h.position.fromArray(data.geometry.vertices,i*3);h.userData.vertexIndex=i;handles.add(h)}if(selectedVertices.size){const c=new THREE.Vector3();selectedVertices.forEach(i=>c.fromArray(data!.geometry.vertices,i*3));c.multiplyScalar(1/selectedVertices.size);pivot(c)}}else if(mode==="edges"){const positions=mesh.geometry.getAttribute("position");const edges=meshEdges(data);for(const e of edges){const a=new THREE.Vector3().fromArray(data.geometry.vertices,e.a*3),b=new THREE.Vector3().fromArray(data.geometry.vertices,e.b*3),g=new THREE.BufferGeometry().setFromPoints([a,b]);const h=new THREE.Line(g,new THREE.LineBasicMaterial({color:selectedEdges.has(edgeKey(e.a,e.b))?"#ffcc00":"#fff",linewidth:3}));h.userData.edgeKey=edgeKey(e.a,e.b);handles.add(h)}if(selectedEdges.size){const c=new THREE.Vector3();let n=0;for(const e of edges)if(selectedEdges.has(edgeKey(e.a,e.b))){c.add(new THREE.Vector3().fromArray(data.geometry.vertices,e.a*3));c.add(new THREE.Vector3().fromArray(data.geometry.vertices,e.b*3));n+=2}if(n)pivot(c.multiplyScalar(1/n))}}else if(mode==="faces"){const positions=mesh.geometry.getAttribute("position");const c=new THREE.Vector3();let n=0;for(const face of selectedFaces){const ids=faceVertexIndices(data,face);if(!ids)continue;const vs=new Float32Array(ids.flatMap(i=>[positions.getX(i),positions.getY(i),positions.getZ(i)]));const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(vs,3));const h=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:"#ffcc00",transparent:true,opacity:.35,side:THREE.DoubleSide,depthWrite:false}));h.userData.faceIndex=face;h.renderOrder=10;handles.add(h);ids.forEach(i=>{c.fromArray(data!.geometry.vertices,i*3);n++;});}if(n){c.multiplyScalar(1/n);pivot(c)}}};
 const onDown=(e:PointerEvent)=>{if(!mesh||!data||transform.dragging)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,camera);if(mode==="vertices"){const h=ray.intersectObjects(handles.children.filter(x=>x.userData.vertexIndex!==undefined),false)[0];if(!h)return;const id=h.object.userData.vertexIndex as number;if(e.shiftKey){if(selectedVertices.has(id))selectedVertices.delete(id);else selectedVertices.add(id)}else selectedVertices=new Set([id]);rebuild();dragSnapshot=[...data.geometry.vertices]}else if(mode==="edges"){const h=ray.intersectObjects(handles.children,false)[0];if(!h)return;const id=String(h.object.userData.edgeKey);if(e.shiftKey){if(selectedEdges.has(id))selectedEdges.delete(id);else selectedEdges.add(id)}else selectedEdges=new Set([id]);rebuild();dragSnapshot=[...data.geometry.vertices]}else if(mode==="faces"){const h=ray.intersectObject(mesh,false)[0];if(h?.faceIndex==null)return;const id=h.faceIndex;if(e.shiftKey){if(selectedFaces.has(id))selectedFaces.delete(id);else selectedFaces.add(id)}else selectedFaces=new Set([id]);rebuild();dragSnapshot=[...data.geometry.vertices]}};
 const onChangeTransform=()=>{if(!data||!dragSnapshot)return;const p=handles.userData.pivot as THREE.Group|undefined;if(!p)return;const original=new THREE.Vector3(),ids=new Set<number>();if(mode==="vertices")selectedVertices.forEach(i=>ids.add(i));else if(mode==="edges")for(const k of selectedEdges){const e=meshEdges(data).find(x=>edgeKey(x.a,x.b)===k);if(e){ids.add(e.a);ids.add(e.b)}}else selectedFaces.forEach(f=>faceVertexIndices(data!,f)?.forEach(i=>ids.add(i)));if(!ids.size)return;ids.forEach(i=>original.fromArray(dragSnapshot!,i*3));const center=new THREE.Vector3();ids.forEach(i=>center.add(new THREE.Vector3().fromArray(dragSnapshot!,i*3)));center.multiplyScalar(1/ids.size);const d=p.position.clone().sub(center);if(d.lengthSq()<1e-10)return;const vertices=[...data.geometry.vertices];ids.forEach(i=>{vertices[i*3]=dragSnapshot![i*3]+d.x;vertices[i*3+1]=dragSnapshot![i*3+1]+d.y;vertices[i*3+2]=dragSnapshot![i*3+2]+d.z});data={...data,geometry:{...data.geometry,vertices}};onChange(data.geometry);dragSnapshot=vertices;p.position.copy(center).add(d)};
 renderer.domElement.addEventListener("pointerdown",onDown);transform.addEventListener("objectChange",onChangeTransform);
 return{setMesh(m,d){mesh=m;data=d;selectedVertices.clear();selectedFaces.clear();selectedEdges.clear();dragSnapshot=null;rebuild()},updateData(d){data=d;rebuild()},setMode(m){mode=m;selectedVertices.clear();selectedFaces.clear();selectedEdges.clear();dragSnapshot=null;transform.detach();rebuild()},setFaceAction(){},extrudeSelectedFace(distance){if(!data||!selectedFaces.size)return;let n=data;[...selectedFaces].sort((a,b)=>b-a).forEach(f=>n=extrudeFace(n,f,distance));data=n;onChange(n.geometry);rebuild()},insetSelectedFace(amount){if(!data||!selectedFaces.size)return;let n=data;for(const f of selectedFaces)n=insetFace(n,f,amount);data=n;onChange(n.geometry);rebuild()},bevelSelectedEdges(amount){if(!data||!selectedEdges.size)return;const n=bevelEdges(data,selectedEdges,amount);data=n;onChange(n.geometry);rebuild()},dispose(){renderer.domElement.removeEventListener("pointerdown",onDown);transform.removeEventListener("objectChange",onChangeTransform);transform.detach();transform.dispose();removePivot();clear();scene.remove(handles)}};
}
