import { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { TransformControls } from "three/examples/jsm/controls/TransformControls.js";
import type { Graphics3DWorld } from "../types";
import { createThreeGeometry } from "../3d-renderer";
import { makeWorkspaceCamera } from "../3d-workspace-camera";
import { updateWorldCamera, updateWorldMesh } from "../3d-workspace-model";
import { createThreeDMeshEditController, type MeshEditMode } from "./ThreeDMeshEditOverlay";
import { ThreeDMeshEditControls } from "./ThreeDMeshEditControls";

export interface ThreeDWorkspaceViewportProps { world: Graphics3DWorld; cameraId: string; selectedId: string | null; mode: "translate" | "rotate" | "scale"; editCamera: boolean; onModeChange: (mode: "translate" | "rotate" | "scale") => void; onSelect: (id: string | null) => void; onChange: (world: Graphics3DWorld) => void; }

export function ThreeDWorkspaceViewport({ world, cameraId, selectedId, mode, editCamera, onModeChange, onSelect, onChange }: ThreeDWorkspaceViewportProps) {
  const hostRef = useRef<HTMLDivElement>(null), objectsRef = useRef(new Map<string, THREE.Mesh>()), transformRef = useRef<TransformControls | null>(null), cameraRef = useRef<THREE.Camera | null>(null), orbitRef = useRef<OrbitControls | null>(null), selectionHelperRef = useRef<THREE.BoxHelper | null>(null), worldRef = useRef(world), selectedRef = useRef<string | null>(selectedId), editCameraRef = useRef(editCamera), meshEditModeRef = useRef<MeshEditMode>("object"), meshEditRef = useRef<ReturnType<typeof createThreeDMeshEditController> | null>(null);
  worldRef.current = world; selectedRef.current = selectedId; editCameraRef.current = editCamera;

  useEffect(() => {
    if (!hostRef.current) return;
    const host = hostRef.current, renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2)); renderer.outputColorSpace = THREE.SRGBColorSpace; host.appendChild(renderer.domElement);
    const scene = new THREE.Scene(); scene.background = new THREE.Color("#15171b"); scene.add(new THREE.GridHelper(20, 20), new THREE.AxesHelper(2)); scene.add(new THREE.AmbientLight("#ffffff", 1.1)); const key = new THREE.DirectionalLight("#ffffff", 2); key.position.set(5, 8, 6); scene.add(key);
    const active = worldRef.current.cameras.find(camera => camera.id === cameraId) ?? worldRef.current.cameras[0];
    if (!active) { renderer.dispose(); renderer.domElement.remove(); return; }
    const camera = makeWorkspaceCamera(active, (host.clientWidth || 800) / (host.clientHeight || 520)); cameraRef.current = camera;
    const orbit = new OrbitControls(camera, renderer.domElement); orbit.enableDamping = true; orbitRef.current = orbit;
    const transform = new TransformControls(camera, renderer.domElement); transformRef.current = transform; scene.add(transform.getHelper());
    const meshEdit = createThreeDMeshEditController(scene, camera, renderer, geometry => { const id = selectedRef.current; if (!id) return; const current = worldRef.current.meshes.find(item => item.id === id); if (!current) return; onChange(updateWorldMesh(worldRef.current, id, { geometry })); }); meshEditRef.current = meshEdit;
    const syncSelection = () => { const selected = selectedRef.current ? objectsRef.current.get(selectedRef.current) : undefined; if (!selectionHelperRef.current) { selectionHelperRef.current = new THREE.BoxHelper(undefined, 0xffff00); scene.add(selectionHelperRef.current); } if (selected && meshEditModeRef.current === "object" && !editCameraRef.current) { selectionHelperRef.current.setFromObject(selected); selectionHelperRef.current.visible = true; } else selectionHelperRef.current.visible = false; };
    const sync = () => { const current = worldRef.current; for (const mesh of current.meshes) { let object = objectsRef.current.get(mesh.id); if (!object) { object = new THREE.Mesh(createThreeGeometry(mesh), new THREE.MeshStandardMaterial({ color: mesh.material?.color ?? "#78a9ff", roughness: mesh.material?.roughness ?? 0.75, metalness: mesh.material?.metalness ?? 0, wireframe: mesh.material?.wireframe ?? false })); object.name = mesh.name ?? mesh.id; object.userData.graphics3DId = mesh.id; scene.add(object); objectsRef.current.set(mesh.id, object); } object.position.set(...mesh.transform.position); object.rotation.set(...mesh.transform.rotation); object.scale.set(...mesh.transform.scale); const material = object.material as THREE.MeshStandardMaterial; material.color.set(mesh.material?.color ?? "#78a9ff"); material.roughness = mesh.material?.roughness ?? 0.75; material.metalness = mesh.material?.metalness ?? 0; material.wireframe = mesh.material?.wireframe ?? false; const currentGeometry = object.geometry.getAttribute("position"); if (currentGeometry.count !== mesh.geometry.vertices.length / 3) { object.geometry.dispose(); object.geometry = createThreeGeometry(mesh); } else { const source = mesh.geometry.vertices; for (let i = 0; i < currentGeometry.count; i++) currentGeometry.setXYZ(i, source[i * 3], source[i * 3 + 1], source[i * 3 + 2]); currentGeometry.needsUpdate = true; object.geometry.computeVertexNormals(); } } for (const [id, object] of objectsRef.current) if (!current.meshes.some(mesh => mesh.id === id)) { scene.remove(object); object.geometry.dispose(); (object.material as THREE.Material).dispose(); objectsRef.current.delete(id); } if (editCameraRef.current) transform.attach(camera); else { const selected = selectedRef.current ? objectsRef.current.get(selectedRef.current) : undefined; if (selected && meshEditModeRef.current === "object") transform.attach(selected); else transform.detach(); } const selectedData = selectedRef.current ? current.meshes.find(item => item.id === selectedRef.current) : undefined; if (meshEditModeRef.current !== "object") meshEdit.updateData(selectedData); syncSelection(); };
    sync();
    const raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2();
    const onPointerDown = (event: PointerEvent) => { if (transform.dragging || editCameraRef.current || meshEditModeRef.current !== "object") return; const rect = renderer.domElement.getBoundingClientRect(); pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1; pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1; raycaster.setFromCamera(pointer, camera); const hit = raycaster.intersectObjects([...objectsRef.current.values()])[0]; onSelect(hit?.object.userData.graphics3DId ?? null); };
    const onDrag = (event: { value: boolean }) => { orbit.enabled = !event.value && !editCameraRef.current && meshEditModeRef.current === "object"; };
    const onObjectChange = () => { if (editCameraRef.current) { const id = worldRef.current.cameras.find(item => item.id === cameraId)?.id; if (!id) return; onChange(updateWorldCamera(worldRef.current, id, { position: camera.position.toArray() as [number, number, number], rotation: camera.rotation.toArray().slice(0, 3) as [number, number, number] })); return; } if (meshEditModeRef.current !== "object") return; const id = selectedRef.current, object = id ? objectsRef.current.get(id) : undefined; if (!object || !id || !worldRef.current.meshes.some(mesh => mesh.id === id)) return; onChange(updateWorldMesh(worldRef.current, id, { transform: { position: object.position.toArray() as [number, number, number], rotation: object.rotation.toArray().slice(0, 3) as [number, number, number], scale: object.scale.toArray() as [number, number, number] } })); selectionHelperRef.current?.setFromObject(object); };
    const frameSelection = () => { const id = selectedRef.current, object = id ? objectsRef.current.get(id) : undefined; if (!object) return; const box = new THREE.Box3().setFromObject(object), center = box.getCenter(new THREE.Vector3()), radius = Math.max(box.getSize(new THREE.Vector3()).length() * 0.6, 1); orbit.target.copy(center); const direction = camera.position.clone().sub(center).normalize(); camera.position.copy(center).add(direction.multiplyScalar(radius * 2)); };
    const onKeyDown = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement || event.target instanceof HTMLSelectElement) return; const keyName = event.key.toLowerCase(); if (keyName === "w" && meshEditModeRef.current === "object") onModeChange("translate"); else if (keyName === "e" && meshEditModeRef.current === "object") onModeChange("rotate"); else if (keyName === "r" && meshEditModeRef.current === "object") onModeChange("scale"); else if (keyName === "f") frameSelection(); else if (keyName === "escape") { onSelect(null); transform.detach(); } else if ((event.key === "Delete" || event.key === "Backspace") && selectedRef.current && !editCameraRef.current && meshEditModeRef.current === "object") { const id = selectedRef.current; onChange({ ...worldRef.current, meshes: worldRef.current.meshes.filter(mesh => mesh.id !== id) }); onSelect(null); } };
    renderer.domElement.addEventListener("pointerdown", onPointerDown); renderer.domElement.addEventListener("keydown", onKeyDown); renderer.domElement.tabIndex = 0; transform.addEventListener("dragging-changed", onDrag); transform.addEventListener("objectChange", onObjectChange);
    const resize = () => { const width = host.clientWidth || 1, height = host.clientHeight || 1; renderer.setSize(width, height, false); if (camera instanceof THREE.PerspectiveCamera) camera.aspect = width / height; camera.updateProjectionMatrix(); }; resize(); window.addEventListener("resize", resize);
    let frame = 0; const animate = () => { frame = requestAnimationFrame(animate); orbit.update(); if (selectionHelperRef.current?.visible) selectionHelperRef.current.update(); renderer.render(scene, camera); }; animate();
    return () => { cancelAnimationFrame(frame); window.removeEventListener("resize", resize); renderer.domElement.removeEventListener("pointerdown", onPointerDown); renderer.domElement.removeEventListener("keydown", onKeyDown); transform.removeEventListener("dragging-changed", onDrag); transform.removeEventListener("objectChange", onObjectChange); meshEdit.dispose(); meshEditRef.current = null; orbit.dispose(); orbitRef.current = null; transform.dispose(); transformRef.current = null; cameraRef.current = null; if (selectionHelperRef.current) { scene.remove(selectionHelperRef.current); selectionHelperRef.current = null; } for (const object of objectsRef.current.values()) { object.geometry.dispose(); (object.material as THREE.Material).dispose(); } objectsRef.current.clear(); renderer.dispose(); renderer.domElement.remove(); };
  }, [cameraId, onChange, onSelect, onModeChange]);

  useEffect(() => { transformRef.current?.setMode(mode); }, [mode]);
  useEffect(() => { if (editCamera) { const camera = cameraRef.current; if (camera) transformRef.current?.attach(camera); meshEditRef.current?.setMode("object"); meshEditModeRef.current = "object"; } else { const object = selectedId ? objectsRef.current.get(selectedId) : undefined; if (object) transformRef.current?.attach(object); else transformRef.current?.detach(); meshEditRef.current?.setMesh(undefined, undefined); } }, [selectedId, editCamera]);
  useEffect(() => { for (const mesh of world.meshes) { const object = objectsRef.current.get(mesh.id); if (object) { object.position.set(...mesh.transform.position); object.rotation.set(...mesh.transform.rotation); object.scale.set(...mesh.transform.scale); } } const camera = world.cameras.find(item => item.id === cameraId); if (camera && cameraRef.current) { cameraRef.current.position.set(...camera.position); cameraRef.current.rotation.set(...camera.rotation); if (cameraRef.current instanceof THREE.PerspectiveCamera) { cameraRef.current.fov = camera.fov ?? 50; cameraRef.current.updateProjectionMatrix(); } } const selected = selectedId ? world.meshes.find(item => item.id === selectedId) : undefined; if (meshEditModeRef.current !== "object") meshEditRef.current?.updateData(selected); const selectedObject = selectedId ? objectsRef.current.get(selectedId) : undefined; if (selectionHelperRef.current && selectedObject && meshEditModeRef.current === "object" && !editCamera) { selectionHelperRef.current.setFromObject(selectedObject); selectionHelperRef.current.visible = true; } else if (selectionHelperRef.current) selectionHelperRef.current.visible = false; }, [world.meshes, world.cameras, cameraId, selectedId, editCamera]);
  const setMeshEditMode = (next: MeshEditMode) => { if (editCamera || !selectedId) return; meshEditModeRef.current = next; transformRef.current?.detach(); meshEditRef.current?.setMode(next); const selected = world.meshes.find(mesh => mesh.id === selectedId); const object = objectsRef.current.get(selectedId); meshEditRef.current?.setMesh(next === "object" ? undefined : object, next === "object" ? undefined : selected); };
  const meshEditMode = meshEditModeRef.current;
  return <div ref={hostRef} tabIndex={0} style={{ minHeight: 520, position: "relative", outline: "none" }}><div style={{ position: "absolute", top: 10, left: 10, zIndex: 2, display: "flex", gap: 6, flexWrap: "wrap" }}><button onClick={() => setMeshEditMode("object")} title="Object mode (Esc)" aria-pressed={meshEditMode === "object"}>Object</button><button onClick={() => setMeshEditMode("vertices")} disabled={!selectedId || editCamera} aria-pressed={meshEditMode === "vertices"}>Vertices</button><button onClick={() => setMeshEditMode("edges")} disabled={!selectedId || editCamera} aria-pressed={meshEditMode === "edges"}>Edges</button><button onClick={() => setMeshEditMode("faces")} disabled={!selectedId || editCamera} aria-pressed={meshEditMode === "faces"}>Faces</button><button onClick={() => onModeChange("translate")} disabled={meshEditMode !== "object"} title="Move (W)" aria-pressed={mode === "translate"}>Move</button><button onClick={() => onModeChange("rotate")} disabled={meshEditMode !== "object"} title="Rotate (E)" aria-pressed={mode === "rotate"}>Rotate</button><button onClick={() => onModeChange("scale")} disabled={meshEditMode !== "object"} title="Scale (R)" aria-pressed={mode === "scale"}>Scale</button><button onClick={() => { const id = selectedRef.current, object = id ? objectsRef.current.get(id) : undefined; if (!object || !orbitRef.current || !cameraRef.current) return; const box = new THREE.Box3().setFromObject(object), center = box.getCenter(new THREE.Vector3()), radius = Math.max(box.getSize(new THREE.Vector3()).length() * 0.6, 1); orbitRef.current.target.copy(center); const direction = cameraRef.current.position.clone().sub(center).normalize(); cameraRef.current.position.copy(center).add(direction.multiplyScalar(radius * 2)); }} disabled={!selectedId} title="Frame selected (F)">Frame</button></div><div style={{ position: "absolute", right: 10, bottom: 10, zIndex: 2, padding: "4px 7px", fontSize: 11, background: "rgba(16,18,22,.75)", borderRadius: 4, pointerEvents: "none" }}>W Move · E Rotate · R Scale · F Frame · Delete Remove · Esc Deselect</div><ThreeDMeshEditControls mode={meshEditMode} controller={meshEditRef.current} disabled={!selectedId || editCamera} /></div>;
}
