import { useMemo, type FC } from "react";
import type { Graphics3DWorld, Graphics3DWorldTimeline } from "../types";
import { interpolateKeyframes } from "../timeline";

export interface WorldTimelinePanelProps { world: Graphics3DWorld; timeline: Graphics3DWorldTimeline; currentTime: number; onSeek:(time:number)=>void; onChange:(timeline:Graphics3DWorldTimeline)=>void; onExit:()=>void; }

export const WorldTimelinePanel:FC<WorldTimelinePanelProps>=({world,timeline,currentTime,onSeek,onChange,onExit})=>{
 const duration=Math.max(0.1,timeline.duration??10);
 const rows=useMemo(()=>timeline.tracks.map(track=>{const target=track.targetType==="mesh"?world.meshes.find(x=>x.id===track.targetId):world.cameras.find(x=>x.id===track.targetId);return {...track,label:`${track.targetType}: ${target?.name??track.targetId} · ${track.property}`};}),[timeline.tracks,world]);
 const addKey=(trackId:string)=>{const track=timeline.tracks.find(x=>x.id===trackId);if(!track)return;const existing=interpolateKeyframes(track.keyframes,currentTime);const value=existing??0;const keyframe={id:`key-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,time:currentTime,value};onChange({...timeline,tracks:timeline.tracks.map(x=>x.id===trackId?{...x,keyframes:[...x.keyframes,keyframe].sort((a,b)=>a.time-b.time)}:x)});};
 return <section className="ge-timeline" aria-label="World timeline"><div className="ge-timeline-subhead" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span>World Timeline · {world.name??world.id}</span><button type="button" onClick={onExit}>← Main Timeline</button></div><div style={{padding:"8px 12px",display:"flex",gap:12,alignItems:"center"}}><span>World time {currentTime.toFixed(2)}s / {duration.toFixed(2)}s</span><button type="button" onClick={()=>onSeek(0)}>⏮</button><label><input type="checkbox" checked={!!timeline.loop} onChange={e=>onChange({...timeline,loop:e.target.checked})}/> Loop</label><label>Duration <input type="number" min="0.1" step="0.1" value={timeline.duration??10} onChange={e=>onChange({...timeline,duration:Math.max(.1,Number(e.target.value)||.1)})}/></label></div><div className="ge-timeline-body" onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek(Math.max(0,Math.min(duration,(e.clientX-r.left)/r.width*duration)));}}>{rows.map(track=><div key={track.id} className="ge-tree-object" style={{padding:"8px 12px"}}><div style={{display:"flex",justifyContent:"space-between"}}><b>{track.label}</b><button type="button" onClick={()=>addKey(track.id)}>+ keyframe</button></div><div style={{position:"relative",height:28,marginTop:4,borderTop:"1px solid #444"}}>{track.keyframes.map(k=><button key={k.id} type="button" title={`${k.time}s = ${k.value}`} style={{position:"absolute",left:`${k.time/duration*100}%`,transform:"translateX(-50%)"}} onClick={e=>{e.stopPropagation();onSeek(k.time)}}>◆</button>)}</div></div>)}</div></section>;
};
