import { useCallback, useState } from "react";
import type { AnimatedProperty, Graphics3DAnimatedProperty, Graphics3DAnimationTarget, Keyframe, Layer } from "../../types";
import type { SceneTimeline as Timeline } from "../../types";
import { add3DTrack, move3DKeyframe, remove3DKeyframe, upsert3DKeyframe } from "../../3d-timeline";
import { createKeyframe, createTrack, moveKeyframe, removeKeyframe, upsertKeyframe } from "../../timeline";

export type SelectedKey = { kind: "2d" | "3d"; trackId: string; keyId: string };
export const useTimelineKeyframes = (timeline: Timeline, onChange: (timeline: Timeline) => void) => {
  const [selectedKey, setSelectedKey] = useState<SelectedKey | null>(null);
  const addTrack = useCallback((layerId: string, property: AnimatedProperty) => { if (timeline.tracks.some(t => t.layerId === layerId && t.property === property)) return; onChange({ ...timeline, tracks: [...timeline.tracks, createTrack(layerId, property)] }); }, [timeline, onChange]);
  const add2DKey = useCallback((layer: Layer, property: AnimatedProperty) => { const track = timeline.tracks.find(t => t.layerId === layer.id && t.property === property); if (!track) return; const value = property === "rotation" ? (layer.rotation ?? 0) : property === "opacity" ? Number(layer.style?.opacity ?? 1) : Number(layer[property]); const scene = timeline.scenes.find(s => timeline.currentTime >= s.start && timeline.currentTime <= s.start + s.duration) ?? timeline.scenes[0]; const time = scene ? Math.max(scene.start, Math.min(timeline.currentTime, scene.start + scene.duration)) : timeline.currentTime; const key = createKeyframe(time, value); onChange({ ...timeline, tracks: timeline.tracks.map(t => t.id === track.id ? upsertKeyframe(t, key) : t) }); setSelectedKey({ kind: "2d", trackId: track.id, keyId: key.id }); }, [timeline, onChange]);
  const add3DKey = useCallback((targetType: Graphics3DAnimationTarget, targetId: string, property: Graphics3DAnimatedProperty, base = 0) => { let next = timeline; let track = timeline.tracks3d?.find(t => t.targetType === targetType && t.targetId === targetId && t.property === property); if (!track) { next = add3DTrack(timeline, targetType, targetId, property); track = next.tracks3d?.find(t => t.targetType === targetType && t.targetId === targetId && t.property === property); } if (!track) return; const key = createKeyframe(next.currentTime, base); next = upsert3DKeyframe(next, track.id, key); onChange(next); setSelectedKey({ kind: "3d", trackId: track.id, keyId: key.id }); }, [timeline, onChange]);
  const move = useCallback((kind: SelectedKey["kind"], trackId: string, keyId: string, time: number) => onChange(kind === "2d" ? { ...timeline, tracks: timeline.tracks.map(t => t.id === trackId ? moveKeyframe(t, keyId, time) : t) } : move3DKeyframe(timeline, trackId, keyId)), [timeline, onChange]);
  const remove = useCallback((kind: SelectedKey["kind"], trackId: string, keyId: string) => { onChange(kind === "2d" ? { ...timeline, tracks: timeline.tracks.map(t => t.id === trackId ? removeKeyframe(t, keyId) : t) } : remove3DKeyframe(timeline, trackId, keyId)); setSelectedKey(current => current?.keyId === keyId ? null : current); }, [timeline, onChange]);
  const patch = useCallback((kind: SelectedKey["kind"], trackId: string, keyId: string, patch: Partial<Pick<Keyframe, "value" | "easing">>) => onChange(kind === "2d" ? { ...timeline, tracks: timeline.tracks.map(t => t.id === trackId ? { ...t, keyframes: t.keyframes.map(k => k.id === keyId ? { ...k, ...patch } : k) } : t) } : { ...timeline, tracks3d: (timeline.tracks3d ?? []).map(t => t.id === trackId ? { ...t, keyframes: t.keyframes.map(k => k.id === keyId ? { ...k, ...patch } : k) } : t) }), [timeline, onChange]);
  return { selectedKey, setSelectedKey, addTrack, add2DKey, add3DKey, move, remove, patch };
};
